plugins:
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.7
  SuggestExtensions: false # stop bugging me with other suggested plugins
  Include:
    - '**/*.rb'
  # DefaultFormatter: pacman

Naming/VariableNumber: # prefer variable_1 over variable1
  EnforcedStyle: snake_case
Style/Documentation: # Don't require documentation comments
  Enabled: false
Metrics/MethodLength: # I dont mind functions with more than 10 lines
  Enabled: false
Metrics/AbcSize: # not that fussed if I have a few more assignments or calls out to other functions that the ideal number
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false